package com.labuda.mateusz;

import java.util.Arrays;

/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/

public class App {

public static void main(String[] args) {
	long sum = 2;
	long[] fibonacciSequence = new long[100_000_000];
	fibonacciSequence[0] = 1;
	fibonacciSequence[1] = 2;
	
	for(int n=2;;n++){
		fibonacciSequence[n] = fibonacciSequence[n-1] + fibonacciSequence[n-2];
		if(fibonacciSequence[n]>4_000_000)
			break;
		if(fibonacciSequence[n]%2==0){
			sum+=fibonacciSequence[n];
		}
	}
	System.out.println(sum);
}
}